//program to print biodata .
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("*******************BIODATA****************************");
printf("\n          welcome to c program");
printf("\n            NAME     :     ABC");
printf("\n         ADDRESS     :     XYZ");
printf("\n             BIO     :     1-7-2015");
printf("\n      CONTACT NO     :     1234567890");
printf("\nPERMNENT ADDRESS     :     IT PARK PB ROAD HUBLI-580029");
printf("\n*******************END OF DETAIL**********************");
getch();
}

