/*//program to print simple message.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf(   " \n\n\n    welcome to c program");
getch();
} */

//program to print biodata.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("\n\n*********************************\n");
printf("\n              Resume");
printf("\n         Name    :    ABC");
printf("\n      Address    :    xyz");
printf("\n          DOB    :    1-1-1111  ");
printf("\n         City    :    HUBLI");
printf("\n\n*********************************\n");
getch();
}