/*//program to find biggest of two no's using if.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
int a=500,b=50;
if(a>b)
printf("\n\n\n A is big",a);
if(a<b)
printf("\n\n\nB is big:=%d",b);
getch();
} */

/*//program to find biggest of two no's using if.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
int a=5,b=5,max=0;
max=(a>b)?a:b;
printf("\n\n %d is big",max);
getch();
} */
/*//program to find biggest of two no's using if else.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
int a,b;
printf("\nEnter the value of A And B:");
scanf("%d%d",&a,&b);
if(a>b)
printf("\n\n\n A is big",a);
//if(a<b)
else
printf("\n\n\nB is big:=%d",b);
getch();
}*/
