//program to print BIODATA.
#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
printf("\n********************BIODATA**************************");
printf("\n              welcome to c program");
printf("\n              NAME       :      ABC");
printf("\n           ADDRESS       :      XYZ");
printf("\n               DOB       :      14-7-2015");
printf("\n    POSTAL ADDRESS       :      IT PARK PB ROAD HUBLI");
printf("\n                                PN0=2357675");
printf("\n                                PIN-580029");
printf("\n**********************************************");
getch();
}