//program to display your BIODATA

#include<iostream.h>
#include<conio.h>

void main()
{
   clrscr();
   cout<<"\n\t*********BIODATA********\n";
   cout<<"\t---------------------------"<<endl;
   cout<<"\tNAME       :AJAY"<<endl;
   cout<<"\tADDRESS    :PATIL"<<endl;
   cout<<"\tCONTACT NO :476689790"<<endl;
   cout<<"\tQUAL       :BE\n";
   cout<<"\tHOBBY      :playing cricket\n";
   cout<<"\t-----------------------------";
   getch();
}