  /*progarm to check the  give year is  leepar or no */
  #include<stdio.h>
  #include<conio.h>
  void main()
    {
  clrscr();
  printf("\n size ofinteger =%d bytes", sizeof (int));
  printf("\n size offloat =%d bytes", sizeof (float));
  printf("\n size ofcharacter =%d bytes", sizeof (char));
  printf("\n size ofdouble =%d bytes", sizeof (double));
  printf("\n size ofsigned =%d bytes", sizeof (signed));
  printf("\n size ofunsigned =%d bytes", sizeof (unsigned));
  printf("\n size of short =%d bytes", sizeof (short));
  printf("\n size oflong =%d bytes", sizeof (long));
  getch();
  }


