#include <iostream.h>
#include<conio.h>



void main()
{
   int x = -1;
    clrscr();
   // Some code
   cout << "Before try \n";
   try {
      cout << "Inside try \n";
      if (x < 0)
      {
	 throw x;
	 cout << "After throw (Never executed) \n";
      }
   }
   catch (int x ) {
      cout << "Exception Caught \n";
   }

   cout << "After catch (Will be executed) \n";
  getch();
}