/*program to demo sizeof operator*/
#include <iostream.h>
#include <conio.h>
void main()
{
 clrscr();
 cout<<"\n size of ineteger="<<sizeof(int);
 cout<<"\n size of float="<<sizeof(float);
 cout<<"\n size of character="<<sizeof(char);
 cout<<"\n size of double="<<sizeof(double);
 cout<<"\n size of signed="<<sizeof(signed);
 cout<<"\n size of unsigned="<<sizeof(unsigned);
 cout<<"\n size of short="<<sizeof(short);
 cout<<"\n size of long="<<sizeof(long);
 getch();
}